### ISSUE TITLE
Missing Files/Folders

### ISSUE THREAD

**Issue by Dontmindmes** [MazeAdmin/Maze#1]
Hey there are a bunch of missing folders, is that just me or did you do that intentionally

**Comment by Anapher** [comment]
Hey,
at the moment, I'm working on publishing this project. I want to integrate it in a CI pipeline, I have to update config files, I have to create a module server, etc. Some files in this repo are missing because I don't know if I want to directly include them in this repo. To answer your question, this repo is not yet ready to be built, even if you would get the files, you would need a module server. I will provide documentation for all that soon.

**Comment by Dontmindmes** [comment]
Any idea on when complete file and working build will be avaliable?

**Comment by Anapher** [comment]
I'm currently trying really hard to get everything up and working, it think it will take another week or two.

**Comment by Dontmindmes** [comment]
Alright thx bro, once it's ready let us know

**Comment by NullFlex** [comment]
any updates on this?

**Comment by Anapher** [comment]
Hey, as you can see, the AppVeyor build already passes, which means that the repo is complete.

**Comment by NullFlex** [comment]
> Hey, as you can see, the AppVeyor build already passes, which means that the repo is complete.

Cool, will check out in a bit
